### ISSUE TITLE
Feature: User can create an entry

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/movie-watcher#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a movie review entry with a title, rating, photoUrl for the movie, and write a review.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the reviews tab, and click the NEW button that will take them to a new movie review form. They can add input per section and it will save. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-04-16 at 12 19 31 PM](https://github.com/connie-chin/movie-watcher/assets/155609517/cdd10b1d-5c78-4fde-b086-12585873a1d1)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] hit endpoints of data that needs to display
- [ ] get all reviews (*)
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to have a home page that looks like the schema
- [ ] add a link to the new button
- [ ] create a component that is a form to make a new movie review entry

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
