### ISSUE TITLE
Feature: User can create a watchlist entry

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/movie-watcher#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a watchlist entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-04-24 at 4 13 09 PM](https://github.com/connie-chin/movie-watcher/assets/155609517/efca7e1f-3c0d-4213-81ba-16eb96db2487)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to add new watchLists table
- [ ] Update `data.sql` to have dummy data

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] hit endpoints of data that needs to display
- [ ] get all watchList entries (*)
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] create a component for watchlist entries
- [ ] Create a component to that matches the figma for watchlist  entry form
- [ ] figure out how to link the plus to add either a watchlist or review

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
