### ISSUE TITLE
Refactor: CSS updates

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/movie-watcher#17]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] ... 
- [ ] - [ ] fix css, add background transparent for delete modal
- [ ] make the is loading page cuter for both forms
- [ ] adjust css to be uniform and fluid
- [ ] make things jump and jiggle and be cute
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
