### ISSUE TITLE
Feature: User can view their reviews. 

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/movie-watcher#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their entries for previous movies they have added. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user clicks save, they can go to the reviews/diary area and see their past logs. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-04-18 at 11 21 37 AM](https://github.com/connie-chin/movie-watcher/assets/155609517/7a06f597-0a3b-473b-b7a5-fe5cc11aa4e0)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to have more dummy data

### ☁️ Server Tasks

- [ ] Update `server.js` to git endpoints for viewing all review entries
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to show the user their list of reviews
- [ ] Update main component to use links and navigate... 
- [ ] update moviereview entry form to link the button to the form
- [ ] go back to setLoading and setError variables
- [ ] adjust css to new design

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
