### ISSUE TITLE
Feature: User can delete review entries.

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/movie-watcher#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their reviews. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a review, and have the option to delete it from their list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-04-21 at 2 55 07 PM](https://github.com/connie-chin/movie-watcher/assets/155609517/4271f6f9-8c59-45de-8507-a226288d1b60)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to have a delete endpoint
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] update data.ts to have a function for deleting

### ⚡ Client Tasks

- [ ] Update component to handle delete button on review entry form, and show that in the review entry list

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ]  cleanup code and make sure everything is consistent
 fix deployment issue with it not loading til a refresh...useEffect I think
 fix css design this weekend
 watch video about password stuff
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
